[package]
name = "obsto"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["rt-multi-thread"] }
object_store = { version = "0.10.1", features = ["aws"] }
futures-util = "0.3.30"
dotenvy = "0.15.7"
